### PR TITLE
Make use of new ACME certmanager package.

### PR DESCRIPTION
**Pull request by rgooch**
This also adds support for HTTP redirect to HTTPS.

### CODE REVIEW

**Comment by cviecco** [comment]
Code looks good to me, but can you add an example of using it on the docs directory?

**Comment by cviecco** [comment]
Also, we need a minimal AWS policy example to use this. Documented here or even better in the golib package.

**Comment by rgooch** [comment]
I'll put a sample AWS policy in the golib package.
PTAL. I suggest hiding whitespace changes to make it easier to review.

**Comment by rgooch** [comment]
https://github.com/Cloud-Foundations/golib/pull/13 is a PR to add sample IAM policy documents.

**Pull request merged**
