### PR TITLE
Adding modules

### PR DESCRIPTION
**Pull request by cviecco**

### CODE REVIEW

**Comment by rgooch** [comment]
Is there a way to build without using modules?

**Comment by cviecco** [comment]
remove the modules files? However I dont know for long that will work.

**Comment by rgooch** [comment]
Is there a command-line flag/environment variable which will ignore modules? If so, let's add that to the current target and add a new build target which doesn't have the flag (and thus will build with modules).

**Comment by cviecco** [comment]
closing for a better one

**Pull request closed without merging**
